/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.dis.practica4;

import java.awt.Color;
import java.awt.Point;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import org.beryx.awt.color.ColorFactory;

/**
 *
 * @author Andres
 */
public class Main extends javax.swing.JFrame {

    int i = 0;
    DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss dd-MM-yyyy");
    Date date;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        historyTextArea.append("Historial:\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        applicationPanel = new javax.swing.JPanel();
        backgroundPanel = new javax.swing.JPanel();
        panelColor = new javax.swing.JComboBox<>();
        panelColorTextField = new javax.swing.JTextField();
        trailPanel = new javax.swing.JPanel();
        changeShape = new javax.swing.JComboBox<>();
        pencilPanel = new javax.swing.JPanel();
        pencilColor = new javax.swing.JComboBox<>();
        pencilColorTextField = new javax.swing.JTextField();
        lienzo2 = new es.ulpgc.dis.practica4.Lienzo();
        historyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTextArea = new javax.swing.JTextArea();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Drawing App");
        setResizable(false);

        backgroundPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Change Background Color"));

        panelColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Blue", "Green", "Grey", "Indigo", "Orange", "Purple", "Red", "Violet", "White", "Yellow" }));
        panelColor.setToolTipText("Background switcher");
        panelColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelColorActionPerformed(evt);
            }
        });

        panelColorTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelColorTextField.setText("Insert RGB");
        panelColorTextField.setToolTipText("Introduce RGB colors separated with comas");
        panelColorTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelColorTextFieldMouseClicked(evt);
            }
        });
        panelColorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelColorTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        trailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Change Trail Form"));

        changeShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oval", "Rectangle" }));
        changeShape.setToolTipText("Change shape of pointer");
        changeShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeShapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trailPanelLayout = new javax.swing.GroupLayout(trailPanel);
        trailPanel.setLayout(trailPanelLayout);
        trailPanelLayout.setHorizontalGroup(
            trailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        trailPanelLayout.setVerticalGroup(
            trailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trailPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(changeShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pencilPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Change Pencil Color"));
        pencilPanel.setPreferredSize(new java.awt.Dimension(157, 23));

        pencilColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Blue", "Green", "Grey", "Indigo", "Orange", "Purple", "Red", "Violet", "White", "Yellow" }));
        pencilColor.setToolTipText("Pencil switcher");
        pencilColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencilColorActionPerformed(evt);
            }
        });

        pencilColorTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pencilColorTextField.setText("Insert RGB");
        pencilColorTextField.setToolTipText("Introduce RGB colors separated with comas");
        pencilColorTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pencilColorTextFieldMouseClicked(evt);
            }
        });
        pencilColorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencilColorTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pencilPanelLayout = new javax.swing.GroupLayout(pencilPanel);
        pencilPanel.setLayout(pencilPanelLayout);
        pencilPanelLayout.setHorizontalGroup(
            pencilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencilPanelLayout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(pencilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pencilColorTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencilColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pencilPanelLayout.setVerticalGroup(
            pencilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pencilColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pencilColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lienzo2.setBackground(new java.awt.Color(255, 255, 255));
        lienzo2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lienzo2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo1MouseMoved(evt);
            }
        });
        lienzo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lienzo1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout applicationPanelLayout = new javax.swing.GroupLayout(applicationPanel);
        applicationPanel.setLayout(applicationPanelLayout);
        applicationPanelLayout.setHorizontalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(applicationPanelLayout.createSequentialGroup()
                        .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(trailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pencilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        applicationPanelLayout.setVerticalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pencilPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("Application", applicationPanel);

        historyTextArea.setEditable(false);
        historyTextArea.setColumns(20);
        historyTextArea.setRows(5);
        jScrollPane1.setViewportView(historyTextArea);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(refreshButton)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(refreshButton)
                .addGap(20, 20, 20))
        );

        tabPanel.addTab("History", historyPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel)
                .addContainerGap())
        );

        tabPanel.getAccessibleContext().setAccessibleName("Application");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelColorActionPerformed
        Color c = ColorFactory.valueOf(panelColor.getSelectedItem().toString());
        lienzo2.setBackground(c);

        date = new Date();
        historyTextArea.append("[" + dateFormat.format(date) + "]" +
                " Has cambiado el color del lienzo a: " 
                + panelColor.getSelectedItem() + "\n");
    }//GEN-LAST:event_panelColorActionPerformed

    private void pencilColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencilColorActionPerformed
        Color c = ColorFactory.valueOf(pencilColor.getSelectedItem().toString());
        lienzo2.setForeground(c);

        date = new Date();
        historyTextArea.append("[" + dateFormat.format(date) + "]" + 
                " Has cambiado el color de la estela a: " + 
                pencilColor.getSelectedItem() + "\n");
    }//GEN-LAST:event_pencilColorActionPerformed

    private void panelColorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelColorTextFieldActionPerformed

        String s = panelColorTextField.getText();
        try {
            Color c = ColorFactory.valueOf("rgb(" + s + ")");
            lienzo2.setBackground(c);

            date = new Date();
            historyTextArea.append("[" + dateFormat.format(date) + "]" + 
                    " Has cambiado el color del lienzo al color con código RGB: " + s + "\n");

        } catch (java.lang.IllegalArgumentException ex) {
            lienzo2.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(null, "RGB not valid, must be the "
                    + "form \"x,x,x\" where \'x\' represents numbers", "Value not valid",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_panelColorTextFieldActionPerformed

    private void panelColorTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelColorTextFieldMouseClicked
        // TODO add your handling code here:
        panelColorTextField.setText("");
    }//GEN-LAST:event_panelColorTextFieldMouseClicked

    private void pencilColorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencilColorTextFieldActionPerformed
        // TODO add your handling code here:
        String s = pencilColorTextField.getText();
        try {
            Color c = ColorFactory.valueOf("rgb(" + s + ")");
            lienzo2.setForeground(c);

            date = new Date();
            historyTextArea.append("[" + dateFormat.format(date) + "]" + 
                    " Has cambiado el color de la estela al color con código RGB: " 
                    + s + "\n");
        } catch (java.lang.IllegalArgumentException ex) {
            lienzo2.setForeground(Color.BLACK);
            JOptionPane.showMessageDialog(null, "RGB not valid, set to default", "Value not valid",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pencilColorTextFieldActionPerformed

    private void pencilColorTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pencilColorTextFieldMouseClicked
        // TODO add your handling code here:
        pencilColorTextField.setText("");
    }//GEN-LAST:event_pencilColorTextFieldMouseClicked

    private void changeShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeShapeActionPerformed
        // TODO add your handling code here:
        int i = changeShape.getSelectedIndex();
        lienzo2.changeShape(i);

        date = new Date();
        historyTextArea.append("[" + dateFormat.format(date) + "]" +
                " Has cambiado la forma de la estela a un: " + changeShape.getSelectedItem()
                + "\n");
    }//GEN-LAST:event_changeShapeActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        historyTextArea.setText("");
        historyTextArea.append("Historial:\n");
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void lienzo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo1MouseExited
        for (int i = 0; i < 5; i++) {
            lienzo2.lista[i] = null;
        }
        date = new Date();
        historyTextArea.append("[" + dateFormat.format(date) + "]" +
                " Has salido del lienzo\n");
        lienzo2.repaint();
    }//GEN-LAST:event_lienzo1MouseExited

    private void lienzo1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo1MouseMoved
        int x = evt.getX();
        int y = evt.getY();
        
        if(++i == 5){
            i = 0;
        }
        
        lienzo2.addPointList(new Point(x, y), i);
        
        date = new Date();
        historyTextArea.append("[" + dateFormat.format(date) + "]" +
                " Has creado una figura en las coordenadas X: " + x + " Y: " + y + "\n");
        lienzo2.repaint();
    }//GEN-LAST:event_lienzo1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel applicationPanel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JComboBox<String> changeShape;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JTextArea historyTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private es.ulpgc.dis.practica4.Lienzo lienzo1;
    private es.ulpgc.dis.practica4.Lienzo lienzo2;
    private javax.swing.JComboBox<String> panelColor;
    private javax.swing.JTextField panelColorTextField;
    private javax.swing.JComboBox<String> pencilColor;
    private javax.swing.JTextField pencilColorTextField;
    private javax.swing.JPanel pencilPanel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JPanel trailPanel;
    // End of variables declaration//GEN-END:variables
}
